### ISSUE TITLE
Breaking changes in v0.4.0?

### ISSUE THREAD

**Issue by alexlawrence** [deltaskelta/docker-alertd#18]
I downloaded the latest version in order to be able to only check for container existence. However, it seems like alerting does not work at all anymore. Sample config:

```
---
duration: 100				# duration in ms between docker API calls
iterations: 0				# number of iterations to run (0 = run forever)

containers:
  - name: foo
    expectedRunning: true

  - name: bar
    expectedRunning: true

  - name: baz

email:
  active: true
  smtp: some.example.com
  password: ...
  port: 587
  from: alerting@example.com
  subject: "monitoring alert"
  to:
    - xyz@example.com
    - abc@example.com
```

When stopping a container expected to be running, nothing happens. 
Any idea what could be wrong?
